// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_platform_middleware from "./routes/(platform)/_middleware.ts";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $character_name_ from "./routes/character/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $search from "./routes/search.tsx";
import * as $CharacterViewer from "./islands/CharacterViewer.tsx";
import * as $SearchViewer from "./islands/SearchViewer.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(platform)/_middleware.ts": $_platform_middleware,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/character/[name].tsx": $character_name_,
    "./routes/index.tsx": $index,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/CharacterViewer.tsx": $CharacterViewer,
    "./islands/SearchViewer.tsx": $SearchViewer,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
